### ISSUE TITLE
welcome again and then?

### ISSUE THREAD

**Issue by kavin-90** [ololoepepe/ololord.js#1]
I installed the Ololord after installing 0.21 redis. Version 2.3 wasn't working at all.

As i have installed it i'm looking for Admin Panel. Homepage only shows WELCOME AGAIN message.
I faced too many difficulties installing canvas and node.js and now this
please help me out now.

**Comment by rngnrs** [comment]
Sup, **kavin-90**.
You must install redis _2.3.0 (or 2.3.1)_. Also, check that /public/templates/custom-home.jst exists. By the way, read installation instruction (https://github.com/ololoepepe/ololord.js/wiki/Setup) **very carefully.**

**Comment by kavin-90** [comment]
I tried redis 2.3.0 (or 2.3.1) but it was a failure. The-redis 0.23 worked and i was able to run ololord somehow. It shows me already built boards only. Thanks i'm gonna try it again.

**Comment by ololoepepe** [comment]
For installation instructions, please, refer to [the Wiki page](https://github.com/ololoepepe/ololord.js/wiki/Setup). If you want to add some custom content (you probably do), please, refer to [the corresponding Wiki page](https://github.com/ololoepepe/ololord.js/wiki/Administration). Note, that currently there is no "admin panel", only /manage.html page for user ban management. In particular, there is no way to add new boards, other than create some .js files in the corresponding direcotory. Maybe this feature will be implemented in some future release.

It would help a lot if you tell exact ololord.js version (is it from the main branch or from the develop one?), your OS name, version and arch, and so on (system package versions, npm package versions, ...). Otherwise it's almost impossible to give any specific instructions other than "RTFM".

**Comment by kavin-90** [comment]
Ohh thanks I thought it has built-in admin panel. 
I'm using Centos 6.7, canvas 1.3.9, cairo 1.8, gcc 4.9, the-redis 0.21. 
Thanks again for fast reply.

**Comment by ololoepepe** [comment]
Centos 7 is recommended. Installing/building some packages (cairo, in particular) is tricky on Centos 6.x. I have not tested ololord.js on that OS. Try using Centos 7 and provide error logs, if any.
